### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by npips1991** [goncaloperes/Project-CodeIgniter-CMS#1]
Where In Database ??

**Comment by goncaloperes** [comment]
@npips1991 thanks for your contact.
You can access the DB [here](https://github.com/goncaloperes/Project-CodeIgniter-CMS/blob/master/Database/cms.sql).

**Comment by buibao** [comment]
![image](https://user-images.githubusercontent.com/22741537/47375253-0fdc0880-d71a-11e8-826f-b6aac8c88d7d.png)
i can not run website with URL http://localhost:8080/cmsproject/admin/login
